start_date:
   day: 1
   month: 1
   year: 2021
   
lastDate:
  day: 1
  month: 2
  year: 2021

sys_bar:
  - C
  - G
  - E
  
freq_done:
 - 'G,2W'
 - 'C,2X'
 - 'E,5X'
 - 'G,2X'


weights:
  - 1 #priority level
  - 1 #No. Obs.
  - 1 #SNR
  - 1 #Multipath
  - 1 #Gaps
  
ileprocent: 90
clustering_method: "KMeans"
MDCA_method: "TOPSIS"
num_points: 100